before:
  hooks:
    - go mod download

project_name: tdep

builds:
  - env: [CGO_ENABLED=1]
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      darwin: darwin
      linux: linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
